language: csharp
solution: MailBody.sln
mono: none
dotnet: 1.0.1
os:
  - linux
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore
  - dotnet build -f netstandard1.4 src/MailBody/
  - dotnet build -f netcoreapp1.0 src/Tests/
  - dotnet test src/Tests/Tests.csproj